### ISSUE TITLE
Build error on 24.11

### ISSUE THREAD

**Issue by olaffreund** [KaylorBen/nixcord#98]
```
evaluation warning: Obsolete Flake attribute `nixcord.homeManagerModules.nixcord' is used. It was renamed to `nixcord.homeModules.nixcord`'.
error:
       … while calling the 'head' builtin
         at /nix/store/52hnnvpyni1n79ra4rqxdcswmd2w3823-source/lib/attrsets.nix:1534:13:
         1533|           if length values == 1 || pred here (elemAt values 1) (head values) then
         1534|             head values
             |             ^
         1535|           else

       … while evaluating the attribute 'value'
         at /nix/store/52hnnvpyni1n79ra4rqxdcswmd2w3823-source/lib/modules.nix:992:7:
          991|     // {
          992|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
          993|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/52hnnvpyni1n79ra4rqxdcswmd2w3823-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `assertions':

       … while evaluating definitions from `/nix/store/1gwc55zbal9yc4vkwy919him039b1r3b-source/nixos/common.nix':

       … while evaluating the error message for definitions for `home-manager.users.olafkfreund.xdg.autostart', which is an option that does not exist

       … while evaluating a definition from `/nix/store/52hnnvpyni1n79ra4rqxdcswmd2w3823-source/flake.nix'

       … while evaluating an attribute `content`

       … while evaluating an attribute `content`

       … while evaluating an attribute `entries`

       … while evaluating the option `home-manager.users.olafkfreund.programs.nixcord.discord.package':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "libgbm" at /nix/store/d9j1kwj21r8ahp8cmid2hayajgw069jk-source/discord.nix:45, did you mean "libXpm", "libabw" or "libaom"?'
```

**Comment by DontEatOreo** [comment]
Should be fixed in 48c997178f0061201e4c67149ba65d66b5740edb

**Comment by Cat-Enjoyer81** [comment]
Maybe I'm doing something wrong but I still have the same error with brand new `nix flake update`:

Flake.lock:
```
     "locked": {
        "lastModified": 1745757380,
        "narHash": "sha256-MfA53mffVwGd1uZlFmUHwrGFSdggXfGzTuOH1DP+vY4=",
        "owner": "kaylorben",
        "repo": "nixcord",
        "rev": "ab84b94df09d4ec856a89083cc8f629db5a2d8d9",
        "type": "github"
```

**Comment by ryand56** [comment]
Same here, I have the same error as before: ERR_PNPM_LOCKFILE_CONFIG_MISMATCH
